name: CI

on:
  push:
    branches:
       - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-test-backend:
     runs-on: ubuntu-latest
     outputs:
        coverage: ${{ steps.test-backend.outputs.report }}
     steps:
     - uses: actions/checkout@v4

     - name: Set on Go
       uses: actions/setup-go@v4
       with:
         go-version: 1.21
         cache-dependencies-path: bugtracker-backend/go.sum

     - name: install go-junit-report
       run: go install github.com/jstemmer/go-junit-report/v2@latest

     - name: Execute backend unit tests
       id:  test-backend
       working-directory: ./bugtracker-backend
       run: |
            go test -json -coverprofile=coverage.out -covermode=atomic ./...
            go tool cover -func=coverage.out -o coverage.txt
         
            echo "## go test coverage report" >>$GITHUB_STEP_SUMMARY 
         
            echo '```' >>$GITHUB_STEP_SUMMARY 
            cat coverage.txt >>$GITHUB_STEP_SUMMARY
            echo '```' >>$GITHUB_STEP_SUMMARY 
         
            echo "report<<EOF" >> $GITHUB_OUTPUT
            cat coverage.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
         
            go test -v ./... 2>&1 | go-junit-report > test-results.xml

     - name: add backend unit test results
       uses: dorny/test-reporter@v1
       if: always()
       with:
         name: backend-unit-report
         path: bugtracker-backend/test-results.xml
         reporter: jest-junit

  unit-test-frontend:
    outputs:
      coverage: ${{ steps.test-frontend.outputs.report }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"
        cache-dependency-path: bugtracker-frontend/package-lock.json

    - name: install node dependencies and execute frontend unit tests
      id: test-frontend
      working-directory: ./bugtracker-frontend
      run: |
           npm ci
           npm test | tee full_output.txt
        
           echo "## frontend test coverage report" >>$GITHUB_STEP_SUMMARY 
        
           #to publish the test coverage in the summary of the workflow
           echo '```' >>$GITHUB_STEP_SUMMARY 
           cat full_output.txt >>$GITHUB_STEP_SUMMARY
           echo '```' >>$GITHUB_STEP_SUMMARY 
        
           #to add frontend coverage in the comment of PR
           echo "report<<EOF" >> $GITHUB_OUTPUT
           cat full_output.txt >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT
        

    - name: upload frontend unit test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: frontend-unit-report
        path: bugtracker-frontend/test-results.xml
        reporter: jest-junit

  create-coverage-comment:
    if: github.event_name == 'pull_request'
    needs: [unit-test-backend,unit-test-frontend]
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
    - name: Create backend coverage in PR comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Backend Coverage Report
          ```
          ${{ needs.unit-test-backend.outputs.coverage }}              
          ```
    - name: create frontend coverage in PR comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Frontend Coverage Report
          ```
          ${{ needs.unit-test-frontend.outputs.coverage }}              
          ```

   #we are running api and e2e in one job as docker takes time to spin up containers so it saves time
  API-N-e2eN-Perf-test:
   needs: [unit-test-backend,unit-test-frontend]
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Launch application
       run : |
            docker compose up --build -d
            npx wait-port http://localhost:8080/api/health -t 30000

     - name: run API test
       working-directory: ./tests-api
       run: |
           npm ci
           npx playwright test

     - name: run E2E test
       working-directory: ./tests-e2e
       env:
          CI: "1" #ci is a env variable used to run tests in headless mode which is in playwright.config.ts file
       run: |
           npm ci
           npx playwright install --with-deps
           npx playwright test

     - name: set up k6 for performance test
       uses: grafana/setup-k6-action@v1

     - name: run performance test
       uses: grafana/run-k6-action@v1
       with:
         path: tests-perf/script.js
         flags: --out json=summary.json

     - name: stop application
       if: always()
       run: |
         docker compose down

     - name: upload API  test results
       if: always()
       uses: actions/upload-artifact@v4
       with:
         name: api-test-report
         path: ./tests-api/test-results/
         retention-days: 30

     - name: upload playwright test results
       if: always()
       uses: actions/upload-artifact@v4 #this actions just takes the file and uploaded it on GH which can be downloaded
       with:
         name: playwright-e2e-report
         path: ./tests-e2e/playwright-report/index.html
         retention-days: 30

     - name: publish API  test results
       if: always()
       uses: dorny/test-reporter@v1  #this actions reads the report and displays it nicely on the GH UI
       with:
         name: api-test-report
         path: ./tests-api/test-results/results.xml
         reporter: jest-junit

     - name: upload performance test results
       if: always()
       uses: actions/upload-artifact@v4
       with:
         name: performance-test-report
         path: summary.json  #path is not mentioned as /.tests-perf/summary.json because ci is adding the file in the root folder itself which is ./test-perf for this job
         retention-days: 30

     - name: upload performance html report
       if: always()
       uses: actions/upload-artifact@v4
       with:
         name: performance-html-report
         path: perf-results.html
         retention-days: 30
